language: ruby
cache: bundler
sudo: false
branches:
  only:
  - atomic-tags
rvm:
  - 2.3.7
  - 2.4.4

# https://github.com/travis-ci/travis-ci/issues/8978
matrix:
  include:
    - rvm: 2.5.1
      before_install:
      - gem update --system
    - rvm: ruby-head
      before_install:
      - gem update --system
  allow_failures:
  - rvm: ruby-head
